# Generated by Django 6.0.1 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(default='Bengaluru', max_length=100)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('meetup', 'Meetup'), ('conference', 'Conference'), ('online', 'Online')], default='meetup', max_length=20)),
                ('seats_total', models.PositiveIntegerField(default=100)),
                ('seats_booked', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
