# Generated by Django 6.0.1 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='One per line')),
                ('instructions', models.TextField()),
                ('category', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('dessert', 'Dessert'), ('snack', 'Snack')], default='veg', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='recipes/')),
                ('prep_time', models.PositiveIntegerField(default=15, help_text='Minutes')),
                ('cook_time', models.PositiveIntegerField(default=30, help_text='Minutes')),
                ('servings', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
