# Generated by Django 6.0.1 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner'), ('featured', 'Featured Post'), ('sidebar', 'Sidebar')], default='banner', max_length=20)),
                ('image', models.ImageField(upload_to='ads/')),
                ('target_url', models.URLField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
