# Generated by Django 6.0.1 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('indian', 'Indian Classical'), ('bollywood', 'Bollywood'), ('indie', 'Indie'), ('folk', 'Folk'), ('electronic', 'Electronic')], default='indie', max_length=20)),
                ('audio_file', models.FileField(blank=True, upload_to='music/')),
                ('cover_art', models.ImageField(blank=True, upload_to='music/covers/')),
                ('duration', models.PositiveIntegerField(default=180, help_text='Seconds')),
                ('plays', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
