# Generated by Django 6.0.1 on 2026-02-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Debit/Credit Card'), ('UPI', 'UPI'), ('COD', 'Cash on Delivery (COD)')], default='Card', max_length=10),
        ),
    ]
