# Generated by Django 6.0.1 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('source', models.CharField(default='The Hindu', max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('art', 'Art & Culture'), ('music', 'Music'), ('film', 'Film'), ('sports', 'Sports')], default='tech', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='news/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
